### ISSUE TITLE
Larger #area to let user zoom out 

### ISSUE THREAD

**Issue by v2lrf** [ondras/wwwsqldesigner#293]
can't have permission to push branch 
## in order to let user zoom out and keep png background when he has large DB 
I do not have any large background with tecno used inside this repo so i have some issues to make it running local, and i was wondering if it could be possible for one of you to fix that little css and update it on www ? 

``` css
/* inside /styles/material-inspired.css*/
#area {
        position: relative;
        background: transparent url(../images/back_dim.png);
        width: 3000px;
        height: 3000px;
        opacity: 0.7;
 }
/* to*/
#area {
        position: relative;
        background: transparent url(../images/back_dim.png);
        width: 100%;
        height: 100%;
        opacity: 0.7;
 }

```

and 

``` css
/* inside /styles/original.css*/
#area {
        position: relative;
        background: transparent url(../images/back.png);
        width: 3000px;
        height: 3000px;
 }
/* to*/
 #area {
        position: relative;
        background: transparent url(../images/back.png);
        width: 100%;
        height: 100%;
 }

```
